- name: Run Chrome container
  docker_container:
    image: selenium/node-chrome:latest
    state: started
    recreate: yes
    name: chrome
    env:
      HUB_HOST: "hub"
      HUB_PORT: "4444"
      NODE_MAX_INSTANCES: 3
      NODE_MAX_SESSION: 3
    networks:
      - name: backend_network
