
- name: Making sure backend docker network exists
  docker_network:
    name: backend_network

- name: Run Zookeeper container
  docker_container:
    image: confluentinc/cp-zookeeper:latest
    state: started
    name: zookeeper
    env:
      ZOOKEEPER_CLIENT_PORT: "2181"
    networks:
      - name: backend_network
        aliases:
          - zookeeper