- name: Archiving streaming components
  archive:
    path: "../streaming"
    dest: "../streaming.tgz"
  delegate_to: localhost
  become: no

- name: Extract streaming components to target
  unarchive:
    src: "../streaming.tgz"
    dest: "{{ phishyme.install_dir }}"

- name: Build Transparency container
  docker_image:
    name: phishyme/transparency
    path: "{{ phishyme.install_dir }}/streaming"
    force: yes

- name: Run Transparency container
  docker_container:
    image: phishyme/transparency
    name: transparency
    state: started
    recreate: yes
    env:
      STREAM_NAME: "nootnoot-transparency"
      STREAM_TYPE: "streaming.transparency"
    networks:
      - name: backend_network
        aliases:
          - transparency