- hosts: all
  tags: ['all', 'core']
  become: yes
  strategy: free
  roles:
    - role: generic
      tags: ['generic']

    - role: docker
      tags: ['docker']


- hosts: backend
  tags: ['backend', 'streamio']
  become: yes
  roles:
    - role: zookeeper
      tags: ['zookeeper']
    - role: kafka
      tags: ['kafka']
    - role: mongodb
      tags: ['mongodb']
    - role: api
      tags: ['api']

- hosts: frontend
  tags: ['frontend', 'streamio']
  become: yes
  roles:
    - role: ui
      tags: ['ui']

- hosts: selenium
  tags: ['selenium', 'streamio']
  become: yes
  roles:
    - role: hub
      tags: ['hub']
    - role: chrome
      tags: ['chrome']

- hosts: proxies
  tags: ['proxies']
  become: yes
  roles:
    - role: certs
      tags: ['certs']
    - role: proxy
      tags: ['proxy'] 

- hosts: streaming
  tags: ['streaming', 'streamio']
  become: yes
  roles:
    - role: transparency
      tags: ['transparency']
    - role: wordmatching
      tags: ['wordmatching']
    - role: scraper
      tags: ['scraper']

# - hosts: backend
#   tags: ['backend', 'utils']
#   become: yes
#   vars_prompt:
#     - name: "login_username"
#       prompt: "Username for Reternal auth"
#       private: no
#     - name: "login_password"
#       prompt: "Password for Reternal auth"
#       private: yes
#   roles:
#     - role: management
#       tags: ['management']
#     - role: usercreate
#       tags: ['usercreate']
#     - role: attck
#       tags: ['attck']
#     - role: mapping
#       tags: ['mapping']
#     - role: commands
#       tags: ['commands']