- include_vars: vault.yml

- name: Making sure backend docker network exists
  docker_network:
    name: backend_network

- name: Making sure default install directory is created
  file:
    path: "{{ phishyme.install_dir }}"
    state: directory

- name: Archiving API components
  archive:
    path: "../api"
    dest: "../api.tgz"
  delegate_to: localhost
  become: no

- name: Extract api components to target
  unarchive:
    src: "../api.tgz"
    dest: "{{ phishyme.install_dir }}"

- name: Build API container
  docker_image:
    name: phishyme/api
    path: "{{ phishyme.install_dir }}/api"
    force: yes

- name: Run API container
  docker_container:
    name: phishyme-api
    image: phishyme/api
    state: started
    recreate: yes
    env:
      JWT_SECRET: "{{ passwords.jwt_secret }}"
      FLASK_SECRET: "{{ passwords.api_secret }}"
      CORS_DOMAIN: "{{ phishyme.cors }}"
      MONGO_PASSWORD: "{{ passwords.mongo_phishyme_pass }}"
      MONGO_USER: "{{ database.user }}"
      MONGO_DB: "{{ database.db }}"
    networks:
      - name: backend_network
        aliases:
          - phishyme-api
