- name: Create proxy config directory
  file:
    path: "{{ proxy_target_dir }}"
    state: directory

- name: Copy NGINX config template
  template:
    src: proxy.conf.j2
    dest: "{{ proxy_target_dir }}/proxy.conf"

- name: Run NGINX container
  docker_container:
    name: phishyme-proxy
    image: nginx
    state: started
    recreate: yes
    networks:
      - name: frontend_network
        aliases:
          - phishyme-proxy
        links:
          - phishyme-ui
      - name: backend_network
        aliases:
          - phishyme-proxy
        links:
          - phishyme-backend
    volumes:
      - "{{ proxy_target_dir }}/proxy.conf:/etc/nginx/conf.d/proxy.conf"
      - "{{ proxy_target_dir }}/tls:/etc/nginx/tls"

    ports:
      - "{{ proxy.api.port }}:{{ proxy.api.port }}"
      - "{{ proxy.ui.port }}:{{ proxy.ui.port }}"
